name: Retail Sales Analytics CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements/Requirements.txt

      - name: Verify Jupyter Notebook
        run: |
          test -f "Jupyter notebooks/Retail_Data_Transformation.ipynb"

      - name: Validate Raw Dataset
        run: |
          python - <<EOF
          import pandas as pd

          files = [
              "Raw Dataset/Customers.csv",
              "Raw Dataset/Orders.csv",
              "Raw Dataset/Products.csv",
              "Raw Dataset/Location.csv"
          ]

          for file in files:
              print("=" * 50)
              print("Reading:", file)

              try:
                  df = pd.read_csv(
                      file,
                      sep=";",
                      encoding="latin1"
                  )

                  print("Rows:", df.shape[0])
                  print("Columns:", df.shape[1])

              except Exception as e:
                  print("Error while reading:", file)
                  print(e)
                  raise

          print("All datasets validated successfully.")
          EOF

      - name: Upload Notebook
        uses: actions/upload-artifact@v4
        with:
          name: Jupyter-Notebook
          path: "Jupyter notebooks/"

      - name: Upload Dashboard
        uses: actions/upload-artifact@v4
        with:
          name: Dashboard
          path: Dashboard/
